branch-defaults:
  master:
    environment: SubtalkServer-env
    group_suffix: null
environment-defaults:
  SubtalkServer-env:
    branch: null
    repository: null
global:
  application_name: subtalk-server
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
